missa/apps/main/urls.py
""" apps/main/urls.py """

from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>/update/', views.update, name='update'),
]

missa/apps/main/models.py
""" apps/main/models.py """

from django.db import models


class Day(models.Model):
    """ Day model. """
    day = models.DateField(
        db_column='Date_messe',
    )
    father = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        db_column='Pere',
    )
    brother = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        db_column='Frere',
    )

    class Meta:
        managed = False
        db_table = 'Messe'

    def __str__(self):
        return '{}: {} servi par {}'.format(str(self.day), self.father if self.father else '-', self.brother if self.brother else '-')

    def date_french(self):
        """ Converts a date into french format. """
        weekdays = ['Lundi', 'Mardi', 'Mercredi',
                    'Jeudi', 'Vendredi', 'Samedi', 'Dimanche']
        months = ['janvier', 'février', 'mars', 'avril', 'mai', 'juin',
                  'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre']
        weekday = weekdays[self.day.weekday()]
        day = self.day.day if self.day.day != 1 else '1er'
        month = months[self.day.month - 1]
        year = self.day.year
        return '{} {} {} {}'.format(weekday, day, month, year)

missa/apps/main/forms.py
""" apps/main/forms.py """

from datetime import date

from django import forms
from django.forms.fields import CharField, DateField
from django.forms.widgets import HiddenInput

from .models import Day


class DateChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return '{}'.format(obj.date_french())


class DayForm(forms.ModelForm):
    """ Form for Day. """
    day = DateField(
        widget=HiddenInput(),
    )
    father = CharField(
        required=False,
    )
    brother = CharField(
        required=False,
    )

    class Meta:
        model = Day
        fields = '__all__'

missa/apps/main/views.py
""" apps/main/views.py """

from datetime import date

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import DayForm
from .models import Day


def home(request):
    """ Home view of missa. """
    days = Day.objects.filter(day__year=date.today().year).order_by('day')
    return render(
        request,
        'main/home.html',
        {
            'days': days,
        }
    )


def update(request, **kwargs):
    """ Update a day. """
    day = Day.objects.get(pk=kwargs['pk'])

    if request.method == 'POST':
        form = DayForm(request.POST, instance=day)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:home'))

    else:
        form = DayForm(instance=day)

    return render(
        request,
        'main/form.html',
        {
            'form': form,
            'day': day,
        }
    )

missa/apps/main/templates/main/form.html
{% extends 'main.html' %}

{% block content %}
    <form method="post" novalidate class="d-flex flex-column align-items-center p-2 m-2">
        {% csrf_token %}

        <h3 class="text-center green my-4">Inscription</h3>
        <h6 class="text-center green mb-4">pour la Messe du {{ day.date_french|lower }}</h6>

        <!-- DAY (hidden input) -->
        {{ form.day }}

        <div>
            <table class="table table-borderless">
                <!-- FATHER -->
                <tr>
                    <td class="green mt-5">Célébrant :</td>
                    <td>{{ form.father }}</td>
                </tr>
    
                <!-- BROTHER -->
                <tr>
                    <td class="green mt-5">Servant :</td>
                    <td>{{ form.brother }}</td>
                </tr>
            </table>
        </div>

        <!-- VALIDATION -->
        <div class="w-100 d-flex flex-column align-items-center">
            <button type="submit" id="btn_validate_billet" class="btn btn-primary mt-5">Valider</button>
        </div>
    </form>
{% endblock content %}

missa/apps/main/templates/main/home.html
{% extends 'main.html' %}

{% block content %}
    <h3 class="green my-3">Messe de 11h30 à Saint-Joseph</h3>

    <div class="col-8 mt-3">
        <table class="table table-striped table-bordered">
            <tr class="text-center">
                <td class="col-3 font-weight-bold">Jour</td>
                <td class="col-3 font-weight-bold">Célébrant</td>
                <td class="col-3 font-weight-bold">Servant</td>
                <td class="col-2 font-weight-bold">Action</td>
            </tr>
            {% for day in days %}
                <tr>
                    <td class="font-weight-bold">{{ day.date_french }}</td>
                    <td class="text-center">{{ day.father|default_if_none:'' }}</td>
                    <td class="text-center">{{ day.brother|default_if_none:'' }}</td>
                    <td class="text-center font-weight-bold"><a href={% url 'main:update' day.pk %}>Je m'inscris !</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}